This cell does load a csv file

In [2]:
import pandas as pd

# Define the file path
file_path = 'data/Melbourn_housing.csv'

# Load the dataset into a DataFrame
df = pd.read_csv(file_path)

# Display the first few rows of the DataFrame to verify
print(df.head())

       Suburb             Address  Rooms Type      Price Method SellerG  \
0  Abbotsford       68 Studley St      2    h        NaN     SS  Jellis
1  Abbotsford        85 Turner St      2    h  1480000.0      S  Biggin
2  Abbotsford     25 Bloomburg St      2    h  1035000.0      S  Biggin
3  Abbotsford  18/659 Victoria St      3    u        NaN     VB  Rounds
4  Abbotsford        5 Charles St      3    h  1465000.0     SP  Biggin

        Date  Distance  Postcode  ...  Bathroom  Car  Landsize  BuildingArea  \
0  3/09/2016       2.5    3067.0  ...       1.0  1.0     126.0           NaN
1  3/12/2016       2.5    3067.0  ...       1.0  1.0     202.0           NaN
2  4/02/2016       2.5    3067.0  ...       1.0  0.0     156.0          79.0
3  4/02/2016       2.5    3067.0  ...       2.0  1.0       0.0           NaN
4  4/03/2017       2.5    3067.0  ...       2.0  0.0     134.0         150.0

   YearBuilt         CouncilArea Lattitude  Longtitude             Regionname  \
0        NaN  Yarra City Council  -37.8014    144.9958  Northern Metropolitan
1        NaN  Yarra City Council  -37.7996    144.9984  Northern Metropolitan
2     1900.0  Yarra City Council  -37.8079    144.9934  Northern Metropolitan
3        NaN  Yarra City Council  -37.8114    145.0116  Northern Metropolitan
4     1900.0  Yarra City Council  -37.8093    144.9944  Northern Metropolitan

  Propertycount
0        4019.0
1        4019.0
2        4019.0
3        4019.0
4        4019.0

[5 rows x 21 columns]

In [3]:
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,3/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.80140,144.99580,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.79960,144.99840,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.80790,144.99340,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,4/02/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.81140,145.01160,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.80930,144.99440,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44408,Yarraville,13 Burns St,4,h,1480000.0,PI,Jas,24/02/2018,6.3,3013.0,...,1.0,3.0,593.0,NaN,NaN,Maribyrnong City Council,-37.81053,144.88467,Western Metropolitan,6543.0
44409,Yarraville,29A Murray St,2,h,888000.0,SP,Sweeney,24/02/2018,6.3,3013.0,...,2.0,1.0,98.0,104.0,2018.0,Maribyrnong City Council,-37.81551,144.88826,Western Metropolitan,6543.0
44410,Yarraville,147A Severn St,2,t,705000.0,S,Jas,24/02/2018,6.3,3013.0,...,1.0,2.0,220.0,120.0,2000.0,Maribyrnong City Council,-37.82286,144.87856,Western Metropolitan,6543.0
44411,Yarraville,12/37 Stephen St,3,h,1140000.0,SP,hockingstuart,24/02/2018,6.3,3013.0,...,NaN,NaN,NaN,NaN,NaN,Maribyrnong City Council,NaN,NaN,Western Metropolitan,6543.0
44412,Yarraville,3 Tarrengower St,2,h,1020000.0,PI,RW,24/02/2018,6.3,3013.0,...,1.0,0.0,250.0,103.0,1930.0,Maribyrnong City Council,-37.81810,144.89351,Western Metropolitan,6543.0

In [4]:
# Remove the 'Method' column
df.drop(columns=['Method'], inplace=True)

In [5]:
df

,Suburb,Address,Rooms,Type,Price,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,Jellis,3/09/2016,2.5,3067.0,2.0,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.80140,144.99580,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,Biggin,3/12/2016,2.5,3067.0,2.0,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.79960,144.99840,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,Biggin,4/02/2016,2.5,3067.0,2.0,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.80790,144.99340,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,Rounds,4/02/2016,2.5,3067.0,3.0,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.81140,145.01160,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,Biggin,4/03/2017,2.5,3067.0,3.0,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.80930,144.99440,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44408,Yarraville,13 Burns St,4,h,1480000.0,Jas,24/02/2018,6.3,3013.0,4.0,1.0,3.0,593.0,NaN,NaN,Maribyrnong City Council,-37.81053,144.88467,Western Metropolitan,6543.0
44409,Yarraville,29A Murray St,2,h,888000.0,Sweeney,24/02/2018,6.3,3013.0,2.0,2.0,1.0,98.0,104.0,2018.0,Maribyrnong City Council,-37.81551,144.88826,Western Metropolitan,6543.0
44410,Yarraville,147A Severn St,2,t,705000.0,Jas,24/02/2018,6.3,3013.0,2.0,1.0,2.0,220.0,120.0,2000.0,Maribyrnong City Council,-37.82286,144.87856,Western Metropolitan,6543.0
44411,Yarraville,12/37 Stephen St,3,h,1140000.0,hockingstuart,24/02/2018,6.3,3013.0,NaN,NaN,NaN,NaN,NaN,NaN,Maribyrnong City Council,NaN,NaN,Western Metropolitan,6543.0
44412,Yarraville,3 Tarrengower St,2,h,1020000.0,RW,24/02/2018,6.3,3013.0,2.0,1.0,0.0,250.0,103.0,1930.0,Maribyrnong City Council,-37.81810,144.89351,Western Metropolitan,6543.0

In [6]:
# Divide the 'Price' column by 1000 and create a new column 'Price K$'
df['Price K$'] = df['Price'] / 1000

# Drop the old 'Price' column
df.drop(columns=['Price'], inplace=True)

In [7]:
df

,Suburb,Address,Rooms,Type,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Price K$
0,Abbotsford,68 Studley St,2,h,Jellis,3/09/2016,2.5,3067.0,2.0,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.80140,144.99580,Northern Metropolitan,4019.0,NaN
1,Abbotsford,85 Turner St,2,h,Biggin,3/12/2016,2.5,3067.0,2.0,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.79960,144.99840,Northern Metropolitan,4019.0,1480.0
2,Abbotsford,25 Bloomburg St,2,h,Biggin,4/02/2016,2.5,3067.0,2.0,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.80790,144.99340,Northern Metropolitan,4019.0,1035.0
3,Abbotsford,18/659 Victoria St,3,u,Rounds,4/02/2016,2.5,3067.0,3.0,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.81140,145.01160,Northern Metropolitan,4019.0,NaN
4,Abbotsford,5 Charles St,3,h,Biggin,4/03/2017,2.5,3067.0,3.0,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.80930,144.99440,Northern Metropolitan,4019.0,1465.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44408,Yarraville,13 Burns St,4,h,Jas,24/02/2018,6.3,3013.0,4.0,1.0,3.0,593.0,NaN,NaN,Maribyrnong City Council,-37.81053,144.88467,Western Metropolitan,6543.0,1480.0
44409,Yarraville,29A Murray St,2,h,Sweeney,24/02/2018,6.3,3013.0,2.0,2.0,1.0,98.0,104.0,2018.0,Maribyrnong City Council,-37.81551,144.88826,Western Metropolitan,6543.0,888.0
44410,Yarraville,147A Severn St,2,t,Jas,24/02/2018,6.3,3013.0,2.0,1.0,2.0,220.0,120.0,2000.0,Maribyrnong City Council,-37.82286,144.87856,Western Metropolitan,6543.0,705.0
44411,Yarraville,12/37 Stephen St,3,h,hockingstuart,24/02/2018,6.3,3013.0,NaN,NaN,NaN,NaN,NaN,NaN,Maribyrnong City Council,NaN,NaN,Western Metropolitan,6543.0,1140.0
44412,Yarraville,3 Tarrengower St,2,h,RW,24/02/2018,6.3,3013.0,2.0,1.0,0.0,250.0,103.0,1930.0,Maribyrnong City Council,-37.81810,144.89351,Western Metropolitan,6543.0,1020.0

In [8]:
# Divide the 'Landsize' column by 4046.86 to convert to acres and create a new column 'Landsize (acres)'
df['Landsize (acres)'] = df['Landsize'] / 4046.86

In [9]:
df

,Suburb,Address,Rooms,Type,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,...,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Price K$,Landsize (acres)
0,Abbotsford,68 Studley St,2,h,Jellis,3/09/2016,2.5,3067.0,2.0,1.0,...,126.0,NaN,NaN,Yarra City Council,-37.80140,144.99580,Northern Metropolitan,4019.0,NaN,0.031135
1,Abbotsford,85 Turner St,2,h,Biggin,3/12/2016,2.5,3067.0,2.0,1.0,...,202.0,NaN,NaN,Yarra City Council,-37.79960,144.99840,Northern Metropolitan,4019.0,1480.0,0.049915
2,Abbotsford,25 Bloomburg St,2,h,Biggin,4/02/2016,2.5,3067.0,2.0,1.0,...,156.0,79.0,1900.0,Yarra City Council,-37.80790,144.99340,Northern Metropolitan,4019.0,1035.0,0.038548
3,Abbotsford,18/659 Victoria St,3,u,Rounds,4/02/2016,2.5,3067.0,3.0,2.0,...,0.0,NaN,NaN,Yarra City Council,-37.81140,145.01160,Northern Metropolitan,4019.0,NaN,0.000000
4,Abbotsford,5 Charles St,3,h,Biggin,4/03/2017,2.5,3067.0,3.0,2.0,...,134.0,150.0,1900.0,Yarra City Council,-37.80930,144.99440,Northern Metropolitan,4019.0,1465.0,0.033112
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44408,Yarraville,13 Burns St,4,h,Jas,24/02/2018,6.3,3013.0,4.0,1.0,...,593.0,NaN,NaN,Maribyrnong City Council,-37.81053,144.88467,Western Metropolitan,6543.0,1480.0,0.146533
44409,Yarraville,29A Murray St,2,h,Sweeney,24/02/2018,6.3,3013.0,2.0,2.0,...,98.0,104.0,2018.0,Maribyrnong City Council,-37.81551,144.88826,Western Metropolitan,6543.0,888.0,0.024216
44410,Yarraville,147A Severn St,2,t,Jas,24/02/2018,6.3,3013.0,2.0,1.0,...,220.0,120.0,2000.0,Maribyrnong City Council,-37.82286,144.87856,Western Metropolitan,6543.0,705.0,0.054363
44411,Yarraville,12/37 Stephen St,3,h,hockingstuart,24/02/2018,6.3,3013.0,NaN,NaN,...,NaN,NaN,NaN,Maribyrnong City Council,NaN,NaN,Western Metropolitan,6543.0,1140.0,NaN
44412,Yarraville,3 Tarrengower St,2,h,RW,24/02/2018,6.3,3013.0,2.0,1.0,...,250.0,103.0,1930.0,Maribyrnong City Council,-37.81810,144.89351,Western Metropolitan,6543.0,1020.0,0.061776

In [10]:
# Function to split the address into number and name parts
def split_address(address):
    import re
    match = re.match(r"(\d+[\w\W]*?)\s(.*)", address)
    if match:
        return match.groups()
    else:
        return address, ""

# Apply the function to the 'Address' column and create new columns
df[['Address Number', 'Address Name']] = df['Address'].apply(split_address).apply(pd.Series)

In [11]:
# Export the DataFrame to a CSV file called 'final.csv'
df.to_csv('final_Melbourn.csv', index=False)

In [12]:
df

,Suburb,Address,Rooms,Type,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,...,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Price K$,Landsize (acres),Address Number,Address Name
0,Abbotsford,68 Studley St,2,h,Jellis,3/09/2016,2.5,3067.0,2.0,1.0,...,NaN,Yarra City Council,-37.80140,144.99580,Northern Metropolitan,4019.0,NaN,0.031135,68,Studley St
1,Abbotsford,85 Turner St,2,h,Biggin,3/12/2016,2.5,3067.0,2.0,1.0,...,NaN,Yarra City Council,-37.79960,144.99840,Northern Metropolitan,4019.0,1480.0,0.049915,85,Turner St
2,Abbotsford,25 Bloomburg St,2,h,Biggin,4/02/2016,2.5,3067.0,2.0,1.0,...,1900.0,Yarra City Council,-37.80790,144.99340,Northern Metropolitan,4019.0,1035.0,0.038548,25,Bloomburg St
3,Abbotsford,18/659 Victoria St,3,u,Rounds,4/02/2016,2.5,3067.0,3.0,2.0,...,NaN,Yarra City Council,-37.81140,145.01160,Northern Metropolitan,4019.0,NaN,0.000000,18/659,Victoria St
4,Abbotsford,5 Charles St,3,h,Biggin,4/03/2017,2.5,3067.0,3.0,2.0,...,1900.0,Yarra City Council,-37.80930,144.99440,Northern Metropolitan,4019.0,1465.0,0.033112,5,Charles St
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44408,Yarraville,13 Burns St,4,h,Jas,24/02/2018,6.3,3013.0,4.0,1.0,...,NaN,Maribyrnong City Council,-37.81053,144.88467,Western Metropolitan,6543.0,1480.0,0.146533,13,Burns St
44409,Yarraville,29A Murray St,2,h,Sweeney,24/02/2018,6.3,3013.0,2.0,2.0,...,2018.0,Maribyrnong City Council,-37.81551,144.88826,Western Metropolitan,6543.0,888.0,0.024216,29A,Murray St
44410,Yarraville,147A Severn St,2,t,Jas,24/02/2018,6.3,3013.0,2.0,1.0,...,2000.0,Maribyrnong City Council,-37.82286,144.87856,Western Metropolitan,6543.0,705.0,0.054363,147A,Severn St
44411,Yarraville,12/37 Stephen St,3,h,hockingstuart,24/02/2018,6.3,3013.0,NaN,NaN,...,NaN,Maribyrnong City Council,NaN,NaN,Western Metropolitan,6543.0,1140.0,NaN,12/37,Stephen St
44412,Yarraville,3 Tarrengower St,2,h,RW,24/02/2018,6.3,3013.0,2.0,1.0,...,1930.0,Maribyrnong City Council,-37.81810,144.89351,Western Metropolitan,6543.0,1020.0,0.061776,3,Tarrengower St

In [13]:
# Function to calculate Haversine distance in meters
def haversine(lat1, lon1, lat2, lon2):
    from math import radians, sin, cos, sqrt, atan2
    
    # Radius of the Earth in meters
    R = 6371000
    
    # Convert latitude and longitude from degrees to radians
    lat1, lon1, lat2, lon2 = map(radians, [lat1, lon1, lat2, lon2])
    
    # Compute differences
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    
    # Haversine formula
    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))
    
    # Distance in meters
    distance = R * c
    return distance

# Coordinates of the reference point
ref_lat = -37.80140
ref_lon = 144.99580

# Calculate distance for each row and create a new column 'Distance (m)'
df['Distance (m)'] = df.apply(lambda row: haversine(ref_lat, ref_lon, row['Lattitude'], row['Longtitude']), axis=1)

In [14]:
df

,Suburb,Address,Rooms,Type,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,...,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Price K$,Landsize (acres),Address Number,Address Name,Distance (m)
0,Abbotsford,68 Studley St,2,h,Jellis,3/09/2016,2.5,3067.0,2.0,1.0,...,Yarra City Council,-37.80140,144.99580,Northern Metropolitan,4019.0,NaN,0.031135,68,Studley St,0.000000
1,Abbotsford,85 Turner St,2,h,Biggin,3/12/2016,2.5,3067.0,2.0,1.0,...,Yarra City Council,-37.79960,144.99840,Northern Metropolitan,4019.0,1480.0,0.049915,85,Turner St,303.717186
2,Abbotsford,25 Bloomburg St,2,h,Biggin,4/02/2016,2.5,3067.0,2.0,1.0,...,Yarra City Council,-37.80790,144.99340,Northern Metropolitan,4019.0,1035.0,0.038548,25,Bloomburg St,752.895372
3,Abbotsford,18/659 Victoria St,3,u,Rounds,4/02/2016,2.5,3067.0,3.0,2.0,...,Yarra City Council,-37.81140,145.01160,Northern Metropolitan,4019.0,NaN,0.000000,18/659,Victoria St,1778.543510
4,Abbotsford,5 Charles St,3,h,Biggin,4/03/2017,2.5,3067.0,3.0,2.0,...,Yarra City Council,-37.80930,144.99440,Northern Metropolitan,4019.0,1465.0,0.033112,5,Charles St,887.008968
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44408,Yarraville,13 Burns St,4,h,Jas,24/02/2018,6.3,3013.0,4.0,1.0,...,Maribyrnong City Council,-37.81053,144.88467,Western Metropolitan,6543.0,1480.0,0.146533,13,Burns St,9815.869541
44409,Yarraville,29A Murray St,2,h,Sweeney,24/02/2018,6.3,3013.0,2.0,2.0,...,Maribyrnong City Council,-37.81551,144.88826,Western Metropolitan,6543.0,888.0,0.024216,29A,Murray St,9576.907813
44410,Yarraville,147A Severn St,2,t,Jas,24/02/2018,6.3,3013.0,2.0,1.0,...,Maribyrnong City Council,-37.82286,144.87856,Western Metropolitan,6543.0,705.0,0.054363,147A,Severn St,10571.982187
44411,Yarraville,12/37 Stephen St,3,h,hockingstuart,24/02/2018,6.3,3013.0,NaN,NaN,...,Maribyrnong City Council,NaN,NaN,Western Metropolitan,6543.0,1140.0,NaN,12/37,Stephen St,NaN
44412,Yarraville,3 Tarrengower St,2,h,RW,24/02/2018,6.3,3013.0,2.0,1.0,...,Maribyrnong City Council,-37.81810,144.89351,Western Metropolitan,6543.0,1020.0,0.061776,3,Tarrengower St,9175.999183

In [15]:

from datetime import datetime

# Get the current date and time
current_datetime = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")


# Define the file name
file_name = f"Conso-{current_datetime}.xlsx"

# Export the DataFrame to an Excel file
df.to_excel(file_name, index=False)

print(f"DataFrame has been exported to '{file_name}'")

DataFrame has been exported to 'Conso-2026-02-25_17-54-50.xlsx'

In [16]:
import plotly.express as px

# 📌 Ensure required columns exist and clean data
if {"Lattitude", "Longtitude", "Type"}.issubset(df.columns):
    df = df.dropna(subset=["Lattitude", "Longtitude", "Type"])  # Remove rows with NaN values

    # 🔹 Convert to numeric to avoid errors
    df["Lattitude"] = pd.to_numeric(df["Lattitude"], errors="coerce")
    df["Longtitude"] = pd.to_numeric(df["Longtitude"], errors="coerce")

    # 🔹 Define a color mapping for the 'Type' column
    color_map = {"u": "blue", "t": "green", "h": "red"}  # Customize colors

    # 🔹 Create the Plotly scatter map
    fig = px.scatter_mapbox(
        df,
        lat="Lattitude",
        lon="Longtitude",
        color="Type",
        color_discrete_map=color_map,
        hover_data=["Type"],  # Show type on hover
        title="Melbourne Housing Locations by Type",
        zoom=10
    )

    # 🔹 Use an OpenStreetMap basemap
    fig.update_layout(
        mapbox_style="open-street-map",
        mapbox_center={"lat": df["Lattitude"].mean(), "lon": df["Longtitude"].mean()},
        margin={"r":0,"t":40,"l":0,"b":0}
    )

    # 🔹 Show the map
    fig.show()

else:
    print("⚠️ The required columns 'Lattitude', 'Longtitude', or 'Type' are missing in the DataFrame.")

/var/folders/yv/wkk87h_51m7f6sk_gxnr53fh0000gn/T/ipykernel_38451/1803492756.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Lattitude"] = pd.to_numeric(df["Lattitude"], errors="coerce")
/var/folders/yv/wkk87h_51m7f6sk_gxnr53fh0000gn/T/ipykernel_38451/1803492756.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Longtitude"] = pd.to_numeric(df["Longtitude"], errors="coerce")
/var/folders/yv/wkk87h_51m7f6sk_gxnr53fh0000gn/T/ipykernel_38451/1803492756.py:15: DeprecationWarning: *scatter_mapbox* is deprecated! Use *scatter_map* instead. Learn more at: https://plotly.com/python/mapbox-to-maplibre/
  fig = px.scatter_mapbox(